ThAmCo.Events/Models/Event.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using ThAmCo.Venues.Data;

namespace ThAmCo.Events.Models
{
    public class Event
    {

        public Event()
        {
            IsDeleted = false;
        }

        public int EventId { get; set; }

        [Required]
        public string Title { get; set; }

        [Display(Name = "Event Date")]
        public DateTime EventDate { get; set; }

        [Required]
        [Display(Name = "Event Type")]
        public string EventType { get; set; }

        public bool IsDeleted { get; set; }

    }
}

ThAmCo.Events/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ThAmCo.Events.DTOs;
using ThAmCo.Events.Models;
using ThAmCo.Events.ViewModels.EventViewModels;

namespace ThAmCo.Events.Controllers
{
    public class EventsController : Controller
    {
        private readonly EventsContext _context;
        public EventsController(EventsContext context)
        {
            _context = context;

        }

        // GET: Events
        public async Task<IActionResult> Index()
        {
            // Ensuring no deleted events are listed
             var eventsList = await _context.Events
                .Where(e => !e.IsDeleted)
                .ToListAsync();

            return View(eventsList);
        }

        // GET: Events/Guests/5
        public async Task<IActionResult> Guests(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // Not returning the requested events if they are deleted
            var @event = await _context
                .Events
                .FirstOrDefaultAsync(m => m.EventId == id && !m.IsDeleted);

            if (@event == null)
            {
                return NotFound();
            }

            // Getting all the guests associated with the event
            var guests = _context.GuestBookings
                .Where(g => g.EventId == id)
                .Include(g => g.Customer)
                .Include(g => g.Event);

            return View(guests);
        }

        // GET: Events/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //Using and populating the view model
            EventDetailsViewModel @event = await _context.Events
                .Select(m => new EventDetailsViewModel
                {
                    EventId = m.EventId,
                    Title = m.Title,
                    EventDate = m.EventDate,
                    EventType = m.EventType
                })
                .FirstOrDefaultAsync(m => m.EventId == id);

            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // GET: Events/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EventId,Title,EventDate,EventType,IsDeleted")] Event @event)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@event);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(@event);
        }

        // GET: Events/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Events.FindAsync(id);
            if (@event == null)
            {
                return NotFound();
            }
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EventId,Title")] EditEventDto @event)
        {
            if (id != @event.EventId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // Getting the event details
                    var @eventDetails = await _context.Events.FindAsync(id);
                    if (@eventDetails == null)
                    {
                        return NotFound();
                    }

                    // Setting the only value of the DTO that should be updated
                    @eventDetails.Title = @event.Title;


                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(@event.EventId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@event);
        }


        // GET: Events/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Events
                .FirstOrDefaultAsync(m => m.EventId == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @event = await _context.Events.FindAsync(id);
            _context.Events.Remove(@event);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventExists(int id)
        {
            return _context.Events.Any(e => e.EventId == id);
        }
    }
}

ThAmCo.Events/Controllers/GuestBookingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ThAmCo.Events.Models;

namespace ThAmCo.Events.Controllers
{
    public class GuestBookingsController : Controller
    {
        private readonly EventsContext _context;

        public GuestBookingsController(EventsContext context)
        {
            _context = context;
        }

        // GET: GuestBookings
        public async Task<IActionResult> Index()
        {
            var eventsContext = _context.GuestBookings
                .Include(g => g.Customer)
                .Include(g => g.Event);

            return View(await eventsContext.ToListAsync());
        }

        // GET: GuestBookings/Details/5
        public async Task<IActionResult> Details(int? id, int? eventId)
        {
            if (id == null)
            {
                return NotFound();
            }

            // Checking the composite key in order to return the right result
            var guestBooking = await _context.GuestBookings
                .Include(g => g.Customer)
                .Include(g => g.Event)
                .FirstOrDefaultAsync(m => m.CustomerId == id && m.EventId == eventId);
            if (guestBooking == null)
            {
                return NotFound();
            }

            return View(guestBooking);
        }

        // GET: GuestBookings/Create
        public IActionResult Create()
        {
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustomerId", "FullName");
            ViewData["EventId"] = new SelectList(_context.Events, "EventId", "Title");
            return View();
        }

        // POST: GuestBookings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EventId,CustomerId")] GuestBooking guestBooking)
        {
            //Checking to see if the record already exists

            var check = _context.GuestBookings.Find(guestBooking.CustomerId, guestBooking.EventId);

            // If the record already exists
            if (check != null)
            {
                ViewData["CustomerId"] = new SelectList(_context.Customers, "CustomerId", "FullName", guestBooking.CustomerId);
                ViewData["EventId"] = new SelectList(_context.Events, "EventId", "EventType", guestBooking.EventId);
                ModelState.AddModelError("EventId", "Key already exists"); // Displaying the error
                return View(guestBooking);
            }

            // If record does not exist
            if (ModelState.IsValid)
            {
                _context.Add(guestBooking);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustomerId", "FullName", guestBooking.CustomerId);
            ViewData["EventId"] = new SelectList(_context.Events, "EventId", "EventType", guestBooking.EventId);
            return View(guestBooking);
        }

        // GET: GuestBookings/Edit/5
        public async Task<IActionResult> Edit(int? id, int? eventId)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guestBooking = await _context.GuestBookings.FindAsync(id, eventId);
            if (guestBooking == null)
            {
                return NotFound();
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustomerId", "FullName", guestBooking.CustomerId);
            ViewData["EventId"] = new SelectList(_context.Events, "EventId", "Title", guestBooking.EventId);
            ViewData["Attendance"] = new SelectList(_context.GuestBookings, "Attendance", "Attendance", guestBooking.Attendance);
            return View(guestBooking);
        }

        // POST: GuestBookings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, int eventId, [Bind("EventId,CustomerId,Attendance")] GuestBooking guestBooking)
        {
            if (id != guestBooking.CustomerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(guestBooking);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GuestBookingExists(guestBooking.CustomerId, guestBooking.EventId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustomerId", "FullName", guestBooking.CustomerId);
            ViewData["EventId"] = new SelectList(_context.Events, "EventId", "Title", guestBooking.EventId);
            ViewData["Attendance"] = new SelectList(_context.GuestBookings, "Attendance", "Attendance", guestBooking.Attendance);
            return View(guestBooking);
        }

        // GET: GuestBookings/Delete/5
        public async Task<IActionResult> Delete(int? id, int? eventId)
        {
            if (id == null)
            {
                return NotFound();
            }

            // Only deleting the record if both keys match
            var guestBooking = await _context.GuestBookings
                .Include(g => g.Customer)
                .Include(g => g.Event)
                .FirstOrDefaultAsync(m => m.CustomerId == id && m.EventId == eventId);
            if (guestBooking == null)
            {
                return NotFound();
            }

            return View(guestBooking);
        }

        // POST: GuestBookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, int? eventId)
        {
            var guestBooking = await _context.GuestBookings.FindAsync(id, eventId);
            _context.GuestBookings.Remove(guestBooking);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GuestBookingExists(int id, int eventId)
        {
            return _context.GuestBookings.Any(e => e.CustomerId == id && e.EventId == eventId);
        }
    }
}

ThAmCo.Events/Views/Events/Create.cshtml
@model ThAmCo.Events.Models.Event

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Event</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventDate" class="control-label"></label>
                <input asp-for="EventDate" class="form-control datepicker" />
                <span asp-validation-for="EventDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventType" class="control-label"></label>
                <input asp-for="EventType" class="form-control" />
                <span asp-validation-for="EventType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function () {
            $(".datepicker").datepicker();
        });
    </script>

}

ThAmCo.Events/Views/Events/Delete.cshtml
@model ThAmCo.Events.Models.Event

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Event</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EventDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EventDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EventType)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EventType)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="EventId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ThAmCo.Events/Views/Events/Details.cshtml
@model ThAmCo.Events.ViewModels.EventViewModels.EventDetailsViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Event</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EventDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EventDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EventType)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EventType)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.EventId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ThAmCo.Events/Views/Events/Edit.cshtml
@model ThAmCo.Events.Models.Event

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Event</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EventId" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventDate" class="control-label"></label>
                <input disabled asp-for="EventDate" class="form-control" />
                <span asp-validation-for="EventDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventType" class="control-label"></label>
                <input disabled asp-for="EventType" class="form-control" />
                <span asp-validation-for="EventType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ThAmCo.Events/Views/Events/Guests.cshtml
@model IEnumerable<ThAmCo.Events.Models.GuestBooking>

@{
    ViewData["Title"] = "Guests";
}

<h1>Guests</h1>
@{ 
    // Getting a total count of guests and displaying it
    var count = 0;
    foreach (var i in Model)
    {
        count += 1;
    }
}
<h2>Total number of guests: @count</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Customer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Event)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Attendance)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Customer.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Event.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Attendance)
            </td>
            <td>
                @Html.ActionLink("Register Attendance", "Edit", "GuestBookings", new { id = item.CustomerId, item.EventId })
            </td>
        </tr>
}
    </tbody>
</table>

ThAmCo.Events/Views/Events/Index.cshtml
@model IEnumerable<ThAmCo.Events.Models.Event>

@{
    ViewData["Title"] = "Index";
}

<h1>Events</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EventDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EventType)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EventDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EventType)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.EventId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.EventId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.EventId">Delete</a> |
                <a asp-action="Guests" asp-route-id="@item.EventId">Guests</a>
                </td>
        </tr>
}
    </tbody>
</table>